# Reparing values
So far, we've dealt with structural issues in data. but there's a lot more to
cleaning.  

Today,  we'll deal with how to fix the values within  the data.
## Cleaning Data review

Instead of more practice with these manipulations, below are more
examples of cleaning data to see how these types of manipulations get used.  
Your goal here is not to memorize every possible thing, but to build a general
idea of what good data looks like and good habits for cleaning data and keeping
it reproducible.  
- [Cleaning the Adult Dataset](https://ryanwingate.com/projects/machine-learning-data-prep/adult/adult-cleaning/)
- [All Shades](https://github.com/the-pudding/data/tree/master/foundation-names#allshadescsv--allshadesr)
Also here are some tips on general data management and organization.

This article is a comprehensive [discussion of data cleaning](https://towardsdatascience.com/the-ultimate-guide-to-data-cleaning-3969843991d4).

### A Cleaning Data Recipe

__not everything possible, but good enough for this course__


1. Can you use parameters to read the data in better?
1. Fix the index and column headers (making these easier to use makes the rest easier)
1. Is the data strucutred well?
1. Are there missing values?
1. Do the datatypes match what you expect by looking at the head or a sample?
1. Are categorical variables represented in usable way?
1. Does your analysis require filtering or augmenting the data?

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np #
na_toy_df_np = pd.DataFrame(data = [[1,3,4,5],[2 ,6, np.nan]])
na_toy_df_pd = pd.DataFrame(data = [[1,3,4,5],[2 ,6, pd.NA]])

# make plots look nicer and increase font size
sns.set_theme(font_scale=2)
arabica_data_url = 'https://raw.githubusercontent.com/jldbc/coffee-quality-database/master/data/arabica_data_cleaned.csv'

coffee_df = pd.read_csv(arabica_data_url,index_col=0)


rhodyprog4ds_gh_events_url = 'https://api.github.com/orgs/rhodyprog4ds/events'
course_gh_df = pd.read_json(rhodyprog4ds_gh_events_url)

## What is clean enough?

This is a great question, without an easy answer.

It depends on what you want to do.  This is why it's important to have potential
questions in mind if you are cleaning data for others *and* why we often have to
do a little bit more preparation after a dataset has been "cleaned"

## Fixing Column names

In [2]:
coffee_df.columns

Index(['Species', 'Owner', 'Country.of.Origin', 'Farm.Name', 'Lot.Number',
       'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner', 'Harvest.Year',
       'Grading.Date', 'Owner.1', 'Variety', 'Processing.Method', 'Aroma',
       'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity',
       'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Total.Cup.Points',
       'Moisture', 'Category.One.Defects', 'Quakers', 'Color',
       'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [3]:
col_name_mapper = {col_name:col_name.lower().replace('.','_') for col_name in coffee_df.columns}

In [4]:
coffee_df.rename(columns=col_name_mapper).head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [5]:
coffee_df.head(1)

,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,Region,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [6]:
coffee_df_fixedcols = coffee_df.rename(columns=col_name_mapper)
coffee_df_fixedcols.head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [7]:
coffee_df_fixedcols['unit_of_measurement'].value_counts()

m     1129
ft     182
Name: unit_of_measurement, dtype: int64

In [8]:
coffee_df_fixedcols['unit_of_measurement'].replace({'m':'meters','ft':'feet'})

1       meters
2       meters
3       meters
4       meters
5       meters
         ...
1307    meters
1308    meters
1309    meters
1310      feet
1312    meters
Name: unit_of_measurement, Length: 1311, dtype: object

In [9]:
coffee_df_fixedcols['unit_of_measurement_long'] = coffee_df_fixedcols['unit_of_measurement'].replace(
                                    {'m':'meters','ft':'feet'})
coffee_df_fixedcols.head(1)

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters,unit_of_measurement_long
1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,guji-hambela,...,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0,meters

## Missing Values


Dealing with missing data is a whole research area. There isn't one solution.


[in 2020 there was a whole workshop on missing](https://artemiss-workshop.github.io/)

one organizer is the main developer of [sci-kit learn](https://scikit-learn.org/stable/) the ML package we will use soon.  In a [2020 invited talk](https://static.sched.com/hosted_files/ray2020/08/Keynote-%20Easier%20Machine%20Learning%20Thoughts%20From%20Scikit-Learn%20-%20Ga%C3%ABl%20Varoquaux%2C%20Research%20Director%2C%20Inria.pdf) he listed more automatic handling as an active area of research  and a development goal for sklearn.

There are also many classic approaches both when training and when [applying models](https://www.jmlr.org/papers/volume8/saar-tsechansky07a/saar-tsechansky07a.pdf).

[example application in breast cancer detection](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.701.4234&rep=rep1&type=pdf)

Even in pandas, dealing with [missing values](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html) is under [experimentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data-na)
 as to how to represent it symbolically


Missing values even causes the [datatypes to change](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data-casting-rules-and-indexing)


That said, there are are om
Pandas gives a few basic tools:

- dropna
- fillna


Dropping is a good choice when you otherwise have a lot of data and the data is
missing at random.

Dropping can be risky if it's not missing at random. For example, if we saw in
the coffee data that one of the scores was missing for all of the rows from one
country, or even just missing more often in one country, that could bias our
results.  

Filling can be good if you know how to fill reasonably, but don't have data to
spare by dropping.  For example
- you can approximate with another column
- you can approximate with that column from other rows

Special case, what if we're filling a summary table?
- filling with a symbol for printing can be a good choice, but not for analysis.

**whatever you do, document it**

In [10]:
coffee_df_fixedcols.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1311 entries, 1 to 1312
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   species                   1311 non-null   object
 1   owner                     1304 non-null   object
 2   country_of_origin         1310 non-null   object
 3   farm_name                 955 non-null    object
 4   lot_number                270 non-null    object
 5   mill                      1001 non-null   object
 6   ico_number                1165 non-null   object
 7   company                   1102 non-null   object
 8   altitude                  1088 non-null   object
 9   region                    1254 non-null   object
 10  producer                  1081 non-null   object
 11  number_of_bags            1311 non-null   int64
 12  bag_weight                1311 non-null   object
 13  in_country_partner        1311 non-null   object
 14  harvest_year              1264 non-null   object
 15  grading_date              1311 non-null   object
 16  owner_1                   1304 non-null   object
 17  variety                   1110 non-null   object
 18  processing_method         1159 non-null   object
 19  aroma                     1311 non-null   float64
 20  flavor                    1311 non-null   float64
 21  aftertaste                1311 non-null   float64
 22  acidity                   1311 non-null   float64
 23  body                      1311 non-null   float64
 24  balance                   1311 non-null   float64
 25  uniformity                1311 non-null   float64
 26  clean_cup                 1311 non-null   float64
 27  sweetness                 1311 non-null   float64
 28  cupper_points             1311 non-null   float64
 29  total_cup_points          1311 non-null   float64
 30  moisture                  1311 non-null   float64
 31  category_one_defects      1311 non-null   int64
 32  quakers                   1310 non-null   float64
 33  color                     1095 non-null   object
 34  category_two_defects      1311 non-null   int64
 35  expiration                1311 non-null   object
 36  certification_body        1311 non-null   object
 37  certification_address     1311 non-null   object
 38  certification_contact     1311 non-null   object
 39  unit_of_measurement       1311 non-null   object
 40  altitude_low_meters       1084 non-null   float64
 41  altitude_high_meters      1084 non-null   float64
 42  altitude_mean_meters      1084 non-null   float64
 43  unit_of_measurement_long  1311 non-null   object
dtypes: float64(16), int64(3), object(25)
memory usage: 460.9+ KB

### Filling missing values 
The 'Lot.Number' has a lot of NaN values, how can we explore it?

We can look at the type:

In [11]:
coffee_df_fixedcols['lot_number'].dtype

dtype('O')

And we can look at the value counts.

In [12]:
coffee_df_fixedcols['lot_number'].value_counts()

1                             18
020/17                         6
019/17                         5
2                              3
102                            3
                              ..
11/23/0696                     1
3-59-2318                      1
8885                           1
5055                           1
017-053-0211/ 017-053-0212     1
Name: lot_number, Length: 221, dtype: int64

We see that a lot are '1', maybe we know that when the data was collected, if the Farm only has one lot, some people recorded '1' and others left it as missing. So we could fill in with 1:

In [13]:
coffee_df_fixedcols['lot_number'].fillna('1')

1                                1
2                                1
3                                1
4                                1
5                                1
                   ...
1307                             1
1308                             1
1309    017-053-0211/ 017-053-0212
1310                             1
1312                           103
Name: lot_number, Length: 1311, dtype: object

Note that even after we called `fillna` we display it again and the original data is unchanged.
To save the filled in column we have a few choices:
- use the `inplace` parameter. This doesn't offer performance advantages, but does It still copies the object, but then reassigns the pointer. Its under discussion to [deprecate](https://github.com/pandas-dev/pandas/issues/16529)
- write to a new DataFrame
- add a column


We'll use adding a column:

In [14]:
coffee_df_fixedcols['lot_number_clean'] = coffee_df_fixedcols['lot_number'].fillna('1')

In [15]:
coffee_df_fixedcols['lot_number_clean'].value_counts()

1                             1059
020/17                           6
019/17                           5
102                              3
103                              3
                              ...
3-59-2318                        1
8885                             1
5055                             1
MCCFWXA15/16                     1
017-053-0211/ 017-053-0212       1
Name: lot_number_clean, Length: 221, dtype: int64

### Dropping missing values
To illustrate how `dropna` works, we'll use the `shape` method:

In [16]:
coffee_df_fixedcols.shape

(1311, 45)

In [17]:
coffee_df_fixedcols.dropna().shape

(130, 45)

By default, it drops any row with one or more `NaN` values.

We could instead tell it to only drop rows with `NaN` in a subset of the columns.

In [18]:
coffee_df_fixedcols.dropna(subset=['altitude_low_meters']).shape

(1084, 45)

In [19]:
coffee_alt_df = coffee_df_fixedcols.dropna(subset=['altitude_low_meters'])

In the [Open Policing Project Data Summary](https://openpolicing.stanford.edu/data/) we saw that they made a summary information that showed which variables had at least 70% not missing values.  We can similarly choose to keep only variables that have more than a specific threshold of data, using the `thresh` parameter and `axis=1` to drop along columns.

In [20]:
n_rows, n_cols = coffee_df_fixedcols.shape
coffee_df_fixedcols.dropna(thresh = .7*n_rows, axis=1).shape

(1311, 44)

This dataset is actually in pretty good shape, but if we use a more stringent threshold it drops more columns.

In [21]:
coffee_df_fixedcols.dropna(thresh = .85*n_rows, axis=1).shape

(1311, 34)

## Inconsistent values


This was one of the things that many of you anticipated or had observed.  A useful way to investigate for this, is to use `value_counts` and sort them alphabetically by the values from the original data, so that similar ones will be consecutive in the list. Once we have the `value_counts()` Series, the values from the `coffee_df` become the index, so we use `sort_index`.

Let's look at the `in_country_partner` column

In [22]:
coffee_df_fixedcols['in_country_partner'].value_counts().sort_index()

AMECAFE                                                                                  205
Africa Fine Coffee Association                                                            49
AlmacafÃ©                                                                                 178
Asociacion Nacional Del CafÃ©                                                             155
AsociaciÃ³n Mexicana De CafÃ©s y CafeterÃ­as De Especialidad A.C.                             6
AsociaciÃ³n de CafÃ©s Especiales de Nicaragua                                                8
Blossom Valley International                                                              58
Blossom Valley International\n                                                             1
Brazil Specialty Coffee Association                                                       67
Central De Organizaciones Productoras De CafÃ© y Cacao Del PerÃº - Central CafÃ© & Cacao      1
Centro AgroecolÃ³gico del CafÃ© A.C.                                                         8
Coffee Quality Institute                                                                   7
Ethiopia Commodity Exchange                                                               18
Instituto HondureÃ±o del CafÃ©                                                              60
Kenya Coffee Traders Association                                                          22
METAD Agricultural Development plc                                                        15
NUCOFFEE                                                                                  36
Salvadoran Coffee Council                                                                 11
Specialty Coffee Ass                                                                       1
Specialty Coffee Association                                                             295
Specialty Coffee Association of Costa Rica                                                42
Specialty Coffee Association of Indonesia                                                 10
Specialty Coffee Institute of Asia                                                        16
Tanzanian Coffee Board                                                                     6
Torch Coffee Lab Yunnan                                                                    2
Uganda Coffee Development Authority                                                       22
Yunnan Coffee Exchange                                                                    12
Name: in_country_partner, dtype: int64

We can see there's only one `Blossom Valley International\n` but 58 `Blossom Valley International`, the former is likely a typo, especially since `\n` is a special character for a newline. Similarly, with 'Specialty Coffee Ass' and 'Specialty Coffee Association'.

In [23]:
partner_corrections = {'Blossom Valley International\n':'Blossom Valley International',
  'Specialty Coffee Ass':'Specialty Coffee Association'}

In [24]:
coffee_df_clean = coffee_df_fixedcols.replace(partner_corrections)

## Example: Unpacking Jsons

In [25]:
rhodyprog4ds_gh_events_url

'https://api.github.com/orgs/rhodyprog4ds/events'

In [26]:
gh_df = pd.read_json(rhodyprog4ds_gh_events_url)
gh_df.head()

,id,type,actor,repo,payload,public,created_at,org
0,27566343224,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128636...",True,2023-03-08 04:20:33+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."
1,27566322788,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128636...",True,2023-03-08 04:18:47+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."
2,27566302748,PushEvent,"{'id': 10656079, 'login': 'brownsarahm', 'disp...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128636...",True,2023-03-08 04:17:02+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."
3,27566292375,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128635...",True,2023-03-08 04:16:08+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."
4,27566280466,PushEvent,"{'id': 10656079, 'login': 'brownsarahm', 'disp...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128635...",True,2023-03-08 04:15:05+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."

Some datasets have a nested structure

We want to transform each one of those from a dictionary like thing into a
row in a data frame.

We can see each row is a Series type.

In [27]:
type(gh_df.loc[0])

pandas.core.series.Series

In [28]:
a= '1'
type(a)

str

Recall, that base python types can be used as function, to cast an object from
type to another.

In [29]:
type(int(a))

int

This works with Pandas Series too

In [30]:
pd.Series(gh_df.loc[0]['actor'])

id                                                        41898282
login                                          github-actions[bot]
display_login                                       github-actions
gravatar_id
url               https://api.github.com/users/github-actions[bot]
avatar_url       https://avatars.githubusercontent.com/u/41898282?
dtype: object

We can use [pandas `apply`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) to do the same thing to every item in a dataset (over rows or columns as items )
For example

In [31]:
gh_df['actor'].apply(pd.Series).head()

,id,login,display_login,gravatar_id,url,avatar_url
0,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
1,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
2,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
3,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
4,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?

compared to the original:

In [32]:
gh_df.head(1)

,id,type,actor,repo,payload,public,created_at,org
0,27566343224,PushEvent,"{'id': 41898282, 'login': 'github-actions[bot]...","{'id': 592944632, 'name': 'rhodyprog4ds/BrownS...","{'repository_id': 592944632, 'push_id': 128636...",True,2023-03-08 04:20:33+00:00,"{'id': 69595187, 'login': 'rhodyprog4ds', 'gra..."

We want to handle several columns this way, so we'll make alist of the names.

In [33]:
js_cols = ['actor','repo','payload','org']

`pd.concat` takes a list of dataframes and puts the together in one DataFrame.

In [34]:
pd.concat([gh_df[col].apply(pd.Series) for col in js_cols],axis=1).head()

,id,login,display_login,gravatar_id,url,avatar_url,id,name,url,repository_id,...,ref_type,master_branch,description,pusher_type,issue,id,login,gravatar_id,url,avatar_url
0,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,592944632,rhodyprog4ds/BrownSpring23,https://api.github.com/repos/rhodyprog4ds/Brow...,592944632.0,...,NaN,NaN,NaN,NaN,NaN,69595187,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
1,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,592944632,rhodyprog4ds/BrownSpring23,https://api.github.com/repos/rhodyprog4ds/Brow...,592944632.0,...,NaN,NaN,NaN,NaN,NaN,69595187,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
2,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,592944632,rhodyprog4ds/BrownSpring23,https://api.github.com/repos/rhodyprog4ds/Brow...,592944632.0,...,NaN,NaN,NaN,NaN,NaN,69595187,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
3,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,592944632,rhodyprog4ds/BrownSpring23,https://api.github.com/repos/rhodyprog4ds/Brow...,592944632.0,...,NaN,NaN,NaN,NaN,NaN,69595187,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
4,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,592944632,rhodyprog4ds/BrownSpring23,https://api.github.com/repos/rhodyprog4ds/Brow...,592944632.0,...,NaN,NaN,NaN,NaN,NaN,69595187,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?

This is close, but a lot of columns have the same name. To fix this we will
 rename the new columns so that they have the original column
name prepended to the new name.

pandas has a rename method for this.

and this is another job for lambdas.

In [35]:
pd.concat([gh_df[col].apply(pd.Series).rename(lambda c: '_'.join([c,col])) for col in js_cols],axis=1).head()

TypeError: sequence item 0: expected str instance, int found

In [36]:
gh_df['actor'].apply(pd.Series).rename(columns=lambda c: '_'.join([c,'actor']))

,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor
0,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
1,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
2,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
3,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
4,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
5,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
6,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
7,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
8,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
9,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
10,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
11,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
12,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
13,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
14,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
15,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
16,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
17,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
18,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
19,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
20,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
21,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
22,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
23,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
24,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
25,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
26,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?
27,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
28,41898282,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?
29,10656079,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?

In [37]:
json_cols_df = pd.concat([gh_df[col].apply(pd.Series).rename(columns=lambda c: '_'.join([c,col])) for col in js_cols],axis=1).head()

In [38]:
gh_df.columns

Index(['id', 'type', 'actor', 'repo', 'payload', 'public', 'created_at',
       'org'],
      dtype='object')

In [39]:
json_cols_df.columns

Index(['id_actor', 'login_actor', 'display_login_actor', 'gravatar_id_actor',
       'url_actor', 'avatar_url_actor', 'id_repo', 'name_repo', 'url_repo',
       'repository_id_payload', 'push_id_payload', 'size_payload',
       'distinct_size_payload', 'ref_payload', 'head_payload',
       'before_payload', 'commits_payload', 'action_payload',
       'release_payload', 'ref_type_payload', 'master_branch_payload',
       'description_payload', 'pusher_type_payload', 'issue_payload', 'id_org',
       'login_org', 'gravatar_id_org', 'url_org', 'avatar_url_org'],
      dtype='object')

Then we can put the two parts of the data together

In [40]:
pd.concat([gh_df[['id','type','public','created_at']],json_cols_df],)

,id,type,public,created_at,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor,...,ref_type_payload,master_branch_payload,description_payload,pusher_type_payload,issue_payload,id_org,login_org,gravatar_id_org,url_org,avatar_url_org
0,2.756634e+10,PushEvent,True,2023-03-08 04:20:33+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.756632e+10,PushEvent,True,2023-03-08 04:18:47+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.756630e+10,PushEvent,True,2023-03-08 04:17:02+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.756629e+10,PushEvent,True,2023-03-08 04:16:08+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.756628e+10,PushEvent,True,2023-03-08 04:15:05+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2.756627e+10,ReleaseEvent,True,2023-03-08 04:13:53+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2.756626e+10,CreateEvent,True,2023-03-08 04:13:22+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.756625e+10,PushEvent,True,2023-03-08 04:12:47+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2.756610e+10,PushEvent,True,2023-03-08 04:00:29+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2.756605e+10,PushEvent,True,2023-03-08 03:57:05+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2.756481e+10,PushEvent,True,2023-03-08 02:20:30+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.756477e+10,PushEvent,True,2023-03-08 02:17:12+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2.756270e+10,IssuesEvent,True,2023-03-07 23:46:48+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2.753462e+10,ReleaseEvent,True,2023-03-07 01:56:11+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2.753461e+10,PushEvent,True,2023-03-07 01:55:20+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2.753458e+10,CreateEvent,True,2023-03-07 01:52:36+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2.753457e+10,PushEvent,True,2023-03-07 01:52:16+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2.742338e+10,PushEvent,True,2023-03-01 18:18:49+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2.742331e+10,PushEvent,True,2023-03-01 18:15:43+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2.741335e+10,PushEvent,True,2023-03-01 12:07:33+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2.741329e+10,CreateEvent,True,2023-03-01 12:05:02+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2.741329e+10,ReleaseEvent,True,2023-03-01 12:05:01+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2.741326e+10,PushEvent,True,2023-03-01 12:03:45+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2.741324e+10,PushEvent,True,2023-03-01 12:02:58+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2.741314e+10,PushEvent,True,2023-03-01 11:59:39+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2.741294e+10,PushEvent,True,2023-03-01 11:51:18+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2.741287e+10,PushEvent,True,2023-03-01 11:48:08+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2.740257e+10,PushEvent,True,2023-03-01 02:35:34+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2.740257e+10,PushEvent,True,2023-03-01 02:34:56+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2.740256e+10,ReleaseEvent,True,2023-03-01 02:34:19+00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaT,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
1,NaN,NaN,NaN,NaT,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
2,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
3,NaN,NaN,NaN,NaT,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
4,NaN,NaN,NaN,NaT,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?

and finally save this

In [41]:
gh_df_clean = pd.concat([gh_df[['id','type','public','created_at']],json_cols_df],axis=1)
gh_df_clean.head()

,id,type,public,created_at,id_actor,login_actor,display_login_actor,gravatar_id_actor,url_actor,avatar_url_actor,...,ref_type_payload,master_branch_payload,description_payload,pusher_type_payload,issue_payload,id_org,login_org,gravatar_id_org,url_org,avatar_url_org
0,27566343224,PushEvent,True,2023-03-08 04:20:33+00:00,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
1,27566322788,PushEvent,True,2023-03-08 04:18:47+00:00,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
2,27566302748,PushEvent,True,2023-03-08 04:17:02+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
3,27566292375,PushEvent,True,2023-03-08 04:16:08+00:00,41898282.0,github-actions[bot],github-actions,,https://api.github.com/users/github-actions[bot],https://avatars.githubusercontent.com/u/41898282?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?
4,27566280466,PushEvent,True,2023-03-08 04:15:05+00:00,10656079.0,brownsarahm,brownsarahm,,https://api.github.com/users/brownsarahm,https://avatars.githubusercontent.com/u/10656079?,...,NaN,NaN,NaN,NaN,NaN,69595187.0,rhodyprog4ds,,https://api.github.com/orgs/rhodyprog4ds,https://avatars.githubusercontent.com/u/69595187?

If we want to analyze this data, this is a good place to save it to disk and start an analysis in  separate notebook.

In [42]:
gh_df_clean.to_csv('gh_events_unpacked.csv')

## Questions After Class

### How the apply function works/use cases?

A4 will give you some examples, espeically the airline dataset. We will also keep seing it come up as we manipulate data more. 

the [apply docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) have tiny examples that help illustrate what it does and some of how it works. The [pandas faq has a section on apply and similar methods](https://pandas.pydata.org/docs/user_guide/gotchas.html#mutating-with-user-defined-function-udf-methods) that gives some more use cases.  

### Is there a better way to see how many missing values?

There are lots of ways. All are fine. We used `info` in class because I was trying to use the way we had already seen.
Info focuses on how many values are *present* instead of what is missing because it makes more sense in most cases. The more common question is: are there enough values to make decisions with?

If you wanted to get counts of the missing values, you can use the pandas [`isna`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html) function.  It is a pandas function, the docs say `pandas.isna` not a DataFrame method (which would be described like `pandas.DataFrame.methodname`). 
This means we use it like

In [43]:
value_to_test = 4
pd.isna(value_to_test)

False

```{admonition} Try it Yourself
pass different values like: `False`, `np.nan` (also `import numpy as np`) and, `pd.NA`, `hello` to this function
```

In [44]:
help(pd.isna)

Help on function isna in module pandas.core.dtypes.missing:

isna(obj: 'object') -> 'bool | npt.NDArray[np.bool_] | NDFrame'
    Detect missing values for an array-like object.

    This function takes a scalar or array-like object and indicates
    whether values are missing (``NaN`` in numeric arrays, ``None`` or ``NaN``
    in object arrays, ``NaT`` in datetimelike).

    Parameters
    ----------
    obj : scalar or array-like
        Object to check for null or missing values.

    Returns
    -------
    bool or array-like of bool
        For scalar input, returns a scalar boolean.
        For array input, returns an array of boolean indicating whether each
        corresponding element is missing.

    See Also
    --------
    notna : Boolean inverse of pandas.isna.
    Series.isna : Detect missing values in a Series.
    DataFrame.isna : Detect missing values in a DataFrame.
    Index.isna : Detect missing values in an Index.

    Examples
    --------
    Scalar arguments (including strings) result in a scalar boolean.

    >>> pd.isna('dog')
    False

    >>> pd.isna(pd.NA)
    True

    >>> pd.isna(np.nan)
    True

    ndarrays result in an ndarray of booleans.

    >>> array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
    >>> array
    array([[ 1., nan,  3.],
           [ 4.,  5., nan]])
    >>> pd.isna(array)
    array([[False,  True, False],
           [False, False,  True]])

    For indexes, an ndarray of booleans is returned.

    >>> index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
    ...                           "2017-07-08"])
    >>> index
    DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'],
                  dtype='datetime64[ns]', freq=None)
    >>> pd.isna(index)
    array([False, False,  True, False])

    For Series and DataFrame, the same type is returned, containing booleans.

    >>> df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])
    >>> df
         0     1    2
    0  ant   bee  cat
    1  dog  None  fly
    >>> pd.isna(df)
           0      1      2
    0  False  False  False
    1  False   True  False

    >>> pd.isna(df[1])
    0    False
    1     True
    Name: 1, dtype: bool

The docstring says that it returns "bool or array-like of bool" but if we go to the website docs that have more examples, we can find out what that it will [return a DataFrame if we pass it a DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.isna.html#:~:text=For%20Series%20and%20DataFrame%2C%20the%20same%20type%20is%20returned%2C%20containing%20booleans). Then we can use the [`pandas.DataFrame.sum`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html) method.

In [45]:
pd.isna(coffee_df_clean).sum()

species                        0
owner                          7
country_of_origin              1
farm_name                    356
lot_number                  1041
mill                         310
ico_number                   146
company                      209
altitude                     223
region                        57
producer                     230
number_of_bags                 0
bag_weight                     0
in_country_partner             0
harvest_year                  47
grading_date                   0
owner_1                        7
variety                      201
processing_method            152
aroma                          0
flavor                         0
aftertaste                     0
acidity                        0
body                           0
balance                        0
uniformity                     0
clean_cup                      0
sweetness                      0
cupper_points                  0
total_cup_points               0
moisture                       0
category_one_defects           0
quakers                        1
color                        216
category_two_defects           0
expiration                     0
certification_body             0
certification_address          0
certification_contact          0
unit_of_measurement            0
altitude_low_meters          227
altitude_high_meters         227
altitude_mean_meters         227
unit_of_measurement_long       0
lot_number_clean               0
dtype: int64

###  in `col_name_mapper = {col_name:col_name.lower().replace('.','_') for col_name in coffee_df.columns}` what is the `{}` for?

This is called a dictionary comphrehension. It is very similar to a [list comprehension](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions). It is one of the [defined ways to build a `dict` type object](https://docs.python.org/3/library/stdtypes.html#dict)

We also saw one when we looked at different types in a [previous class](2023-02-02.md).

In [46]:
{char:i for i,char in enumerate('abcde')}

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}

[`enumerate`](https://docs.python.org/3/library/functions.html#enumerate) is a built in function that 
iterates over items in an iterable type(list-like) and pops the each value paired with its index within
the structure.  

This way we get each character and it's position. We could use this as follows

In [47]:
num_chars = {char:i for i,char in enumerate('abcde')}
alpha_data = ['a','d','e','c','b',']

SyntaxError: EOL while scanning string literal (<ipython-input-47-23657ae6a1c7>, line 2)